### ISSUE TITLE
make error: elen.dic is not created

### ISSUE THREAD

**Issue by s-n-g** [squibbylinux/LibreGreek#3]
Here's what I get:

```
# make
Traceback (most recent call last):
  File "./capitals_no_accent", line 14, in <module>
    uline = line.decode('utf-8').upper()
AttributeError: 'str' object has no attribute 'decode'
Makefile:4: recipe for target 'elen.dic' failed
make: *** [elen.dic] Error 1
```

This is because **capitals_no_accent** is a python 2 script, but python 3 is now used
I have successfully built it using this script

```
#!/usr/bin/python
# -*- coding: utf-8  -*-

import sys

intab = u'ΆΈΉΊΌΎΏΪ'
outab = u'ΑΕΗΙΟΥΩΙ'
trtab = dict((ord(a), b) for a, b in zip(intab, outab))

fin = open(sys.argv[1],"r")
fout = open(sys.argv[2],"w")

if sys.version_info > (3,0):
    for line in fin:
        uline = line.upper()
        uline = uline.translate(trtab)
        fout.write(uline)
else:
    for line in fin:
        uline = line.decode('utf-8').upper()
        uline = uline.translate(trtab)
        eline = uline.encode('utf-8')
        fout.write(eline)

```

**Comment by pkt** [comment]
Hi, good catch!

I think the problem can be fixed in an easier way though, please test the latest
commit whether it produces the correct result.

Thanks again!

**Comment by nickraptis** [comment]
@pkt I was about to suggest the same solutions as the latest commit but I got suspicious of [this note in the python2.7 docs for codecs.open](https://docs.python.org/2/library/codecs.html#codecs.open):

Files are always opened in binary mode, even if no binary mode was specified. This is done to avoid data loss due to encodings using 8-bit values. This means that no automatic conversion of '\n' is done on reading and writing.

I can't say if it matters here, but I wanted to bring it up.

**Comment by pkt** [comment]
I think this would only matter in case this dictionary starts getting developers that prefer to work in windows, which doesn't seem very likely now or in the immediate future. So, if I understood correctly, I don't think this issue is very important.

**Comment by s-n-g** [comment]
Ok, just tested both the dictionary creation and with LO and it seems ok.
I think this issue can be closed

Thanks
